### ISSUE TITLE
Auto Completion has bad display for CJK characters

### ISSUE THREAD

**Issue by UlyssesWu** [waf/PrettyPrompt#1]
This is how it looks like in a Chinese environment with a monospaced font:
(width of 1 Chinese character = width of 2 ASCII characters)

![image](https://user-images.githubusercontent.com/4312781/120205227-4aa46680-c25c-11eb-9673-9d162adddd12.png)

![GIF 2021-5-31 22-19-04](https://user-images.githubusercontent.com/4312781/120206971-6872cb00-c25e-11eb-8623-6c3d46302af9.gif)

**Comment by waf** [comment]
Yikes, thanks for the report. Would you be able to tell me the font you're using in the terminal, as well as your current code page (from the terminal properties window, assuming you're using conhost)? Thanks!

**Comment by UlyssesWu** [comment]
Here is the font:
[font.zip](https://github.com/waf/PrettyPrompt/files/6571095/font.zip)

Code page: 936 (I also switched to 65001 and nothing changes)

The display is same no matter on cmd or Powershell, conhost or Windows Terminal.

**Comment by waf** [comment]
Thanks, I'll work on this over the next couple days.

**Comment by UlyssesWu** [comment]
Sorry, just found the font I provided is not actually "monospace" when used in Windows Terminal. You can still test with it in conhost or powershell.exe .

For WT you can test with this font:
[font-mono.zip](https://github.com/waf/PrettyPrompt/files/6571873/font-mono.zip)

**Comment by waf** [comment]
Thanks, I'm able to use those fonts and reproduce this locally. 👍

**Comment by waf** [comment]
Just a self-note for implementation, some sort of lookup table like https://gist.github.com/gongdo/0275b9ad1f25ad9d6f7a92ff677f5ec0 seems to be required. Other built-in APIs like `System.Rune` and `System.Globalization.StringInfo` don't appear to return the required character width.

**Comment by UlyssesWu** [comment]
Searched for that and found: https://github.com/spectreconsole/wcwidth
They also built a beautiful console library: https://github.com/spectreconsole/spectre.console

**Comment by waf** [comment]
Nice! Yeah, I love Spectre, I'll see how they're using that package in their main project, as well.

**Comment by waf** [comment]
@UlyssesWu I have a branch available here, if you'd like to try out an early version of it: https://github.com/waf/PrettyPrompt/tree/support-full-width-cjk-characters . Please let me know if you find any issues!

It's not 100% done, but it's pretty close. I'm working through some cases related to deleting characters.

**Comment by UlyssesWu** [comment]
Yes it's working as expected. Thanks! 👍

...except the issue you've mentioned, when typing `apple.pear`:
![image](https://user-images.githubusercontent.com/4312781/120882943-22768800-c60d-11eb-8094-cc8be55b2df9.png)

**Comment by waf** [comment]
This has shipped in PrettyPrompt 0.9.5, thanks for reporting it, and testing out that branch. I'll release a new version of csharprepl with the updated dependency in the next few days.

**Comment by UlyssesWu** [comment]
Thanks for the fix. But I can still observe some minor issue:
Type "apple", it's still OK:
![image](https://user-images.githubusercontent.com/4312781/120924185-fb02e680-c704-11eb-8a93-82cc380ea413.png)

Continue to type "." :
![image](https://user-images.githubusercontent.com/4312781/120924206-1241d400-c705-11eb-8a47-676c544c1be0.png)

There is an extra "h".

`apple.pe` :

![image](https://user-images.githubusercontent.com/4312781/120924239-33a2c000-c705-11eb-9e8e-da7ce982b707.png)

The `Fruits` I used:
```
            ( "apple", "苹果the round fruit of a tree of the rose family, which typically has thin red or green skin and crisp flesh. Many varieties have been developed as dessert or cooking fruit or for making cider.", AnsiColor.BrightRed ),
            ( "pear", "梨a yellowish- or brownish-green edible fruit that is typically narrow at the stalk and wider toward the base, with sweet, slightly gritty flesh.", AnsiColor.Green ),
            ( "peach", "桃a round stone fruit with juicy yellow flesh and downy pinkish-yellow skin.", AnsiColor.RGB(255, 229, 180) ),
```

**Comment by waf** [comment]
Thanks for the heads up, reopening

**Comment by waf** [comment]
I've found a better way to model this, which solves the above scenarios and a bunch of other edge cases. Just working through support for syntax highlighting CJK characters, then we should have full support for CJK input / completion.

**Comment by waf** [comment]
@UlyssesWu when you get a chance, could you please try the latest `main` branch? It now handles everything I've tried, including your test cases from above, but I'd like to make sure it works with your environment. Thanks!

**Comment by UlyssesWu** [comment]
Thanks for the fix, it works well! I will test csharprepl when the next version comes out.

**Comment by waf** [comment]
Great to hear! Thanks for your help with describing and testing this issue. I've added you to the [Contributors](https://github.com/waf/PrettyPrompt/blob/main/CONTRIBUTORS.md).

I've published a new version of csharprepl that includes this change. You can update via `dotnet tool update -g csharprepl` (it can sometimes take some minutes for the package to be fully available for download).

Thanks again!

**Comment by UlyssesWu** [comment]
![image](https://user-images.githubusercontent.com/4312781/121779492-7addf480-cbce-11eb-8308-7f15e63043da.png)
IT IS AWESOME.
Thanks again for the great work
