### ISSUE TITLE
Inability to get to start of long multiline inputs

### ISSUE THREAD

**Issue by kindermannhubert** [waf/PrettyPrompt#251]
Write multiline output that will scroll the window. Try to get back to input start (which is now scrolled outside of the window) with arrows or backspace - you can't.

**Comment by kindermannhubert** [comment]
This might be solvable on Windows (via somehow updating WindowTop), but changing WindowTop on other platforms is not supported.

**Comment by waf** [comment]
Closing this due to the new-ish input scrolling feature.
