### ISSUE TITLE
Input needs to be length-limited so it fits into console buffer

### ISSUE THREAD

**Issue by kindermannhubert** [waf/PrettyPrompt#257]
This is a sub-issue of #251.

When an application runs in cmd.exe `Console.BufferHeight` corresponds to the settings of cmd.exe:
![image](https://user-images.githubusercontent.com/11704036/232318615-c9c57db9-1821-4ea9-870b-b6891fd25431.png)
That's good.

But when it runs from Windows Terminal `Console.BufferHeight` is set to window height and it does not matter what number is in:
![image](https://user-images.githubusercontent.com/11704036/232318813-1261e9f7-be24-4975-a83a-9aec8fc6beb2.png)
Windows Terminal history scrolling is independent of the running application (that is probably the same behavior as I observed on Linux). But we can programmatically change `Console.BufferHeight` (and we most probably will with a resolution of #251).

On Linux `Console.BufferHeight` setter API is unfortunately not available. In the Ubuntu terminal `Console.BufferHeight` is also set to window height. I don't know if an application can be started there with a larger buffer height.

The consequence of insufficient buffer height is that when we write longer input that can fit into the console buffer we're then unable to programmatically scroll back to the start of the input. Therefore we should limit the height of the input so it fits into the console buffer.

**Comment by waf** [comment]
Closing this, now we have some rudimentary input scrolling now when content doesn't fit in the console window.
