### ISSUE TITLE
Missing part of border for longer completion item's documentation

### ISSUE THREAD

**Issue by kindermannhubert** [waf/PrettyPrompt#51]
![image](https://user-images.githubusercontent.com/11704036/147885923-f0d2688c-02e8-489e-b97b-020b5d9c74f0.png)

**Comment by waf** [comment]
Ah yeah, this was a stylistic choice I made, but I'm happy to revisit; the common box drawing characters don't support exactly what we need to perfectly draw the three-line joint between the completion box and documentation box.

Rather than drawing an incomplete line, I left the line off entirely!
