### ISSUE TITLE
Completions for arguments and options

### ISSUE THREAD

**Issue by tengl** [waf/PrettyPrompt#56]
First, great project! Exactly what I needed right now.

I just started developing a tool based on `System.CommandLine` and got `PrettyPrompt` working. I'm using `Command` classes with sub-commands (`command.AddCommand(subCommand)`). 

The tool can execute commands directly with `tool command1 arg1 --option1 234` or just start `tool` which starts the REPL with PrettyPrompt. 

I created my own completion which just uses the `rootCommand` to identify which command you are typing. I would like to have completion with arguments, where the `ReplacementText` is the actual typed text, but the `DisplayText` is the name of the argument. E.g. 
```
> command1 ar
               ┌─────────┬─────────────────────────────┐
               │firstArg │ This is the first argument  │
               └─────────┴─────────────────────────────┘
```

I got this working for letters, but not for numbers. 

```
> command1 234
```

It seems that `CompletionCallback` isn't called for numbers or other characters, only letters. It seems to be by design, what is the motivation for that? Options are in the format `--option1` and argument can be anything. 

I'd like `CompletionCallback` to be called for every "word", no matter what it starts with. That way I can decide whether there should be any completions or not. 

(I'm not sure if what I'm trying to do will actually work (for more complex commands with more than 1 argument), but I would like to try it out)

**Comment by kindermannhubert** [comment]
Hi,

I believe you want to use a custom callback in ```PromptCallbacks.OpenCompletionWindowCallback```.

Current default behavior indeed requires the first character of a word to be a letter:
https://github.com/waf/PrettyPrompt/blob/27acbbbc6422c3336e22a7e6fb0c7a53a7643406/src/PrettyPrompt/Panes/CompletionPane.cs#L268-L273
and this callback allows you to override this behavior.

**Comment by tengl** [comment]
> I believe you want to use a custom callback in `PromptCallbacks.OpenCompletionWindowCallback`.

Thanks, I got it working now. I changed the behavior so it would 
* Open directly on new word (' ') 
* Open if you start typing a word but need to backspace and correct the word
* Opens on initial digits as well

Here's the code if anyone else want the same behavior. 

```csharp
new PromptCallbacks
{
    OpenCompletionWindowCallback = (text, caret) =>
    {
        if (caret > 0 && text[caret - 1] is '.' or '(' or ' ') // typical "intellisense behavior", opens for new methods and parameters
        {
            return Task.FromResult(0);
        }

        if (caret == 1 && !char.IsWhiteSpace(text[0]) // 1 word character typed in brand new prompt
            && (text.Length == 1 || !char.IsLetterOrDigit(text[1]))) // if there's more than one character on the prompt, but we're typing a new word at the beginning (e.g. "a| bar")
        {
            return Task.FromResult(1);
        }

        // open when we're starting a new "word" in the prompt or correcting and existing word
        return caret - 2 >= 0
            && char.IsLetterOrDigit(text[caret - 1])
            ? Task.FromResult(1)
            : Task.FromResult(-1);
    }
}
```
