### ISSUE TITLE
Cannot fully see the suggestion box

### ISSUE THREAD

**Issue by realivanjx** [waf/PrettyPrompt#6]
Thanks for this cool tool!
When i tried to use suggestion box, i got this:
![image](https://user-images.githubusercontent.com/12814796/120238812-2dd15880-c287-11eb-933e-93c6b5fd762f.png)

Cannot scroll to the end and see the suggestions fully. I am using Powershell 7 there.

**Comment by waf** [comment]
This has shipped in PrettyPrompt 0.9.5 -- thanks for your help! I'll be releasing another version of csharprepl with the updated dependency in the next day or two. Thanks!

**Comment by waf** [comment]
This has been released as part of csharprepl, version [0.2.3](https://www.nuget.org/packages/CSharpRepl/0.2.3). Thanks again! You can update via `dotnet tool update -g csharprepl`
